//
// Copyright (c) 2017-2020 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

[[required-apis]]
== Required APIs

Compliant implementations of MicroProfile 4.0 must provide at least the following APIs and minimum versions.
These APIs and versions guarantee application developers a minimum set of APIs and are not intended to be restrictive.
Implementations may include APIs not listed below as well they may support more recent versions than what is listed below.

MicroProfile applications that make use of APIs or versions not mentioned below are not considered portable.

 - <<javase, Java SE 8>>
 - <<jakarta-cdi, CDI (Jakarta Contexts and Dependency Injection) 2.0>>
 - <<jakarta-jaxrs, JAX-RS (Jakarta RESTful Web Services) 2.1>>
 - <<jakarta-jsonb, JSON-B (Jakarta JSON Binding) 1.0>>
 - <<jakarta-jsonp, JSON-P (Jakarta JSON Processing) 1.1>>
 - <<jakarta-annotations, Jakarta Annotations 1.3>>
 - <<mp-config, MicroProfile Config 1.4>>
 - <<mp-fault-tolerance, MicroProfile Fault Tolerance 2.1>>
 - <<mp-health-check, MicroProfile Health 2.2>>
 - <<mp-jwt-auth, MicroProfile JWT Authentication 1.1>>
 - <<mp-metrics, MicroProfile Metrics 2.3>>
 - <<mp-openapi, MicroProfile OpenAPI 1.1>>
 - <<mp-opentracing, MicroProfile OpenTracing 1.3>>
 - <<mp-rest-client, MicroProfile Rest Client 1.4>>

[[javase]]
=== Java SE 8

Libraries in use by the MicroProfile leverage new features provided in Java SE 8, therefore Java SE 7 and before are unsupported.
MicroProfile 4.x implementations may provide support for Java SE 9 and beyond, however Java SE 8 compatibility must be maintained.

[[jakarta-cdi]]
=== Jakarta Contexts and Dependency Injection (CDI) 2.0

Jakarta CDI provides the base for a growing number of APIs included in MicroProfile 4.0.
Use of implementations beyond CDI 2.0 in MicroProfile is allowed, however, not required.

 - https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html
 - http://cdi-spec.org/

[[jakarta-jaxrs]]
=== Jakarta RESTful Web Services (JAX-RS) 2.1

Jakarta JAX-RS provides both standard client and server APIs for RESTful communication by MicroProfile 4.0 applications.
Use of implementations beyond JAX-RS 2.1 in MicroProfile is allowed, however, not required as of version 4.0 of MicroProfile.

 - https://jakarta.ee/specifications/restful-ws/2.1/restful-ws-spec-2.1.html
 - https://github.com/eclipse-ee4j/jaxrs-api

[[jakarta-jsonb]]
=== Jakarta JSON-B 1.0

Jakarta JSON-B is leveraged as part of MicroProfile 4.0 to provide standard APIs for binding JSON documents to Java code.
Use of implementations beyond JSON-B 1.0 in MicroProfile is allowed, however, not required.

 - https://jakarta.ee/specifications/jsonb/1.0/jsonb-spec-1.0.html
 - https://github.com/eclipse-ee4j/jsonb-api

[[jakarta-jsonp]]
=== Jakarta JSON-P 1.1

Jakarta JSON-P is leveraged as part of MicroProfile 4.0 to provide standard APIs for processing JSON documents.
Use of implementations beyond JSON-P 1.1 in MicroProfile is allowed, however, not required.

 - https://jakarta.ee/specifications/jsonp/1.1/jsonp-spec-1.1.html
 - https://github.com/eclipse-ee4j/jsonp

[[jakarta-annotations]]
=== Jakarta Annotations 1.3

Jakarta Annotations provides annotations for common semantic concepts across a variety of individual technologies in the Java(TM) SE and Jakarta EE platforms.
Use of implementations beyond Jakarta Annotations 1.3 in MicroProfile is allowed, however, not required.

 - https://jakarta.ee/specifications/annotations/1.3/annotations-spec-1.3.html
 - https://github.com/eclipse-ee4j/common-annotations-api

[[mp-config]]
=== MicroProfile Config 2.0-M1

MicroProfile Config provides applications and microservices means to obtain configuration properties through several environment-aware sources both internal and external to the application and made available through dependency injection or lookup.

 - http://microprofile.io/project/eclipse/microprofile-config
 - https://github.com/eclipse/microprofile-config/releases/tag/2.0-M1

[[mp-fault-tolerance]]
=== MicroProfile Fault Tolerance 3.0-RC1

MicroProfile Fault Tolerance provides the ability to separate execution logic from business logic.
Key aspects of the API include TimeOut, RetryPolicy, Fallback, Bulkhead, and Circuit Breaker processing.
Fault Tolerance 3.0 is now dependent on Jakarta EE 8 technologies.

 - http://microprofile.io/project/eclipse/microprofile-fault-tolerance
 - https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/3.0-RC1

[[mp-health-check]]
=== MicroProfile Health 3.0-RC3

MicroProfile Health provides the ability to expose the health of an application
to the underlying platform (ex: Kubernetes)

 - http://microprofile.io/project/eclipse/microprofile-health
 - https://github.com/eclipse/microprofile-health/releases/tag/3.0-RC3

[[mp-jwt-auth]]
=== MicroProfile JWT Authentication 1.2-RC1

MicroProfile JWT Authentication provides role based access control (RBAC) microservice endpoints using OpenID Connect (OIDC) and JSON Web Tokens (JWT).

 - http://microprofile.io/project/eclipse/microprofile-jwt-auth
 - https://github.com/eclipse/microprofile-jwt-auth/releases/tag/1.2-RC1

[[mp-metrics]]
=== MicroProfile Metrics 3.0-RC1

MicroProfile Metrics provides a unified way for MicroProfile applications to export monitoring data to management agents.
Metrics will also provide a common Java API for exposing their telemetry data.

 - http://microprofile.io/project/eclipse/microprofile-metrics
 - https://github.com/eclipse/microprofile-metrics/releases/tag/3.0-RC1

[[mp-open-api]]
=== MicroProfile OpenAPI 2.0-RC2

MicroProfile OpenAPI provides a unified Java API for the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md[OpenAPI v3 specification] that all application developers can use to expose their API documentation.

 - http://microprofile.io/project/eclipse/microprofile-open-api
 - https://github.com/eclipse/microprofile-open-api/releases/tag/2.0-RC2

[[mp-opentracing]]
=== MicroProfile OpenTracing 2.0-RC1

MicroProfile OpenTracing defines an API and associated behaviors that allow services to easily participate in a distributed tracing environment.

 - http://microprofile.io/project/eclipse/microprofile-opentracing
 - https://github.com/eclipse/microprofile-opentracing/releases/tag/2.0-RC1

[[mp-rest-client]]
=== MicroProfile Rest Client 2.0-RC2

MicroProfile Rest Client provides a type-safe approach for invoking RESTful services over HTTP.
The MicroProfile Rest Client builds upon the https://github.com/eclipse-ee4j/jaxrs-api[JAX-RS 2.1 APIs] for consistency and ease-of-use.

- http://microprofile.io/project/eclipse/microprofile-rest-client
- https://github.com/eclipse/microprofile-rest-client/releases/tag/2.0-RC2
