//
// Copyright (c) 2017-2017 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

[[required-apis]]
== Required APIs

Compliant implementations of Eclipse MicroProfile 1.1 must provide at least the following APIs and minimum versions.  These APIs and versions guarantee application developers a minimum set of APIs and are not intended to be restrictive.  Implementations may include APIs not listed below as well they may support more recent versions that what is listed below.

MicroProfile applications that make use of APIs or versions not mentioned below are not considered portable.

 - Java SE 8
 - Contexts and Dependency Injection for Java EE (CDI) 1.2
 - JAX-RS 2.0.1
 - JSON-P 1.0
 - Eclipse MicroProfile Config 1.0

=== Java SE 8

Libraries in use by the MicroProfile leverage new features provided in Java SE 8, therefore Java SE 7 and before are unsupported.  MicroProfile 1.1 implementations may provide support for Java SE 9 and beyond, however Java SE 8 compatibility must maintained.

=== Contexts and Dependency Injection for Java EE (CDI) 1.2

CDI provides the base for a growing number of APIs included in MicroProfile 1.1.  Use of CDI 2.0 in MicroProfile implementations is allowed, however, not required as of version 1.1 of the MicroProfile.

 - http://cdi-spec.org/
 - https://jcp.org/en/jsr/detail?id=346

=== JAX-RS 2.0.1

JAX-RS provides both standard client and server APIs for RESTful communication by MicroProfile 1.1 applications.  Use of JAX_RS 2.1 in MicroProfile implementations is allowed, however, not required as of version 1.1 of the MicroProfile.

 - https://github.com/jax-rs
 - https://jcp.org/en/jsr/detail?id=339

=== JavaTM API for JSON Processing (JSONP) 1.0

JSONP is leveraged as part of MicroProfile 1.1 to provide standard APIs for processing JSON documents.  Use of JSONP 1.1 in MicroProfile implementations is allowed, however, not required as of version 1.1 of the MicroProfile.

 - https://javaee.github.io/jsonp/
 - https://jcp.org/en/jsr/detail?id=353

=== Eclipse MicroProfile Config 1.0

Eclipse MicroProfile Config provides applications and microservices means to obtain configuration properties through several environment-aware sources both internal and external to the application and made available through dependency injection or lookup.

 - http://microprofile.io/project/eclipse/microprofile-config
 - https://github.com/eclipse/microprofile-config/releases/tag/1.0
