= Frequently Asked Questions

. <<What is the Microprofile?>>
.. <<What is the relationship with Java EE?>>
.. <<What is the relationship with the JCP?>>
. <<Who is involved?>>
. <<How can I get involved?>>
.. <<How do I join?>>
.. <<How do I submit a proposal?>>
. <<What are the logo restrictions?>>

=== What is the Microprofile?
Microprofile is a specification for a microservice-focused platform.

===== What is the relationship with Java EE?
There is no formal relationship with Java EE. The 1.0 specification of Microprofile was based on three APIs (CDI, JSON-P and JAX-RS) which are Java EE APIs, but the specification is not limited to Java EE in the APIs that can be included. Brand new APIs are equally as valid as established APIs.

===== What is the relationship with the JCP?
Microprofile is not governed by the JCP. It is currently (_Dec 2016_) in the process of joining the link:https://eclipse.org/org/foundation/[Eclipse Foundation].

=== Who is involved?
Current vendors implementing version 1.0 of the Microprofile include:

* Red Hat (WildFly Swarm)
* IBM (WebSphere Liberty)
* Payara (Payara Microprofile)
* Tomitribe (TomEE Microprofile)
* Hammock (Microprofile distribution)

There are many individuals who contribute to the Microprofile project. The Java community as a whole is encouraged to take part and contribute to the project; there are no restrictions.

=== How can I get involved?
* Read through, comment on, and create new topics on the link:https://groups.google.com/forum/#!forum/microprofile[Microprofile Google Group]
* Test the sample apps, fix bugs and submit a pull request, or create a new one
* Submit a proposal

===== How do I join?
There is no formal "joining" process, since anyone is welcome to join the discussion in the link:https://groups.google.com/forum/#!forum/microprofile[Google Group].  Depending on how involved you want to be, however, you may want to join the Eclipse Foundation to contribute to the project 

===== How do I submit a proposal?
A process has been created specifically for the evolution of the Microprofile, and can be found under link:https://github.com/microprofile/evolution/blob/master/process.md[the microprofile organisation on GitHub].

=== What are the logo restrictions?
Use of branding for any vendor is subject to the restrictions of that vendor.