= Getting Started with Eclipse MicroProfile

The MicroProfile is a set of APIs and specifications developed within the Eclipse foundation by many parties from the Java community. It doesn't provide any reference implementation but specifies the API and behavior of MicroProfile implementations. It also provides basic information to get started with particular implementations, which already support MicroProfile. Any other vendor is free to implement MicroProfile or a specific API from MicroProfile.

== Creating a MicroProfile project with Maven

Version 1.0 of MicroProfile was released before the project was moved to be under the Eclipse Foundation, so the Maven coordinates are a little different. To create a project which targets version 1.0 of MicroProfile - including JAX-RS 2.0, CDI 1.1 and JSON-P 1.0 - you should include the following dependency:

[source, xml]
---
<dependency>
    <groupId>io.microprofile</groupId>
    <artifactId>microprofile</artifactId>
    <version>1.0.0</version>
    <scope>provided</scope>
</dependency>
---

== What does each specification contain?


[cols=",a", options="header"]
|===
|Version
|Specifications

| 1.0
| 
* JAX-RS 2.0
* CDI 1.1
* JSON-P 1.0

| 1.1
|
* JAX-RS 2.0
* CDI 1.1
* JSON-P 1.0
* http://microprofile.io/project/eclipse/microprofile-config[Config 1.0]

|===

== Implementations

Version 1.0 of MicroProfile is implemented by:

* Apache TomEE
* IBM Websphere Liberty
* KumuluzEE
* https://docs.payara.fish/documentation/payara-micro/payara-micro.html[Payara Micro]
* WildFly Swarm
