//
// Copyright (c) 2017-2017 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

image:https://badges.gitter.im/eclipse/microprofile-bom.svg[link="https://gitter.im/eclipse/microprofile-bom"]

# Eclipse MicroProfile "Bill of Materials"
Eclipse github repository for defining the content of the MicroProfile deliverables.

## Usage
Add this dependency (adjusting the version number appropriately) to your project's pom.xml:

[source,xml]
----
<project ...>
...
    <dependencies>
        <dependency>
            <groupId>org.eclipse.microprofile</groupId>
            <artifactId>microprofile</artifactId>
            <version>1.3</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
----

You will then be able to work with all the APIs supported by MicroProfile implementations.

[NOTE]
This style of BOM does not go in a <dependencyManagement>...</dependencyManagement> section, using import scope, and you cannot add dependencies declared in the BOM without version elements as is typically done with that style of BOM.
