= Eclipse Foundation

The Eclipse MicroProfile proposal is currently in the link:https://www.eclipse.org/projects/dev_process/development_process.php#6_2_2_Proposal[proposal phase] (as of 6th December 2016) and is currently link:https://groups.google.com/d/msg/microprofile/sYMlGBI1qiM/3pphFou0BQAJ[pending an Eclipse board meeting] to discuss the proposal and decide on whether or not to accept it.

The full discussion on the proposal can be viewed in the MicroProfile Google Group post "link:https://groups.google.com/forum/#!topic/microprofile/sYMlGBI1qiM[Discuss Eclipse Foundation proposal]"

=== Why the Foundation?
Assuming the proposal is accepted, it will move to the Eclipse Incubation Phase, which will give a structucture around which we can develop "link:https://www.eclipse.org/projects/dev_process/development_process.php#6_2_3_Incubation[the process, the community, and the technology]".

It quickly became apparent, after the MicroProfile effort began, that formal governance was needed to make sure the project remained transparent and open to contributions in a clear way. Rather than create a bespoke governance model, link:https://groups.google.com/d/msg/microprofile/Y_8YCYa0JZ4/9o40cGjsBgAJ[there was a discussion about the issue] and link:https://groups.google.com/d/msg/microprofile/aVX7G4QTP0A/CIrfzTn1GQAJ[the decision was taken to move the project to the Eclipse Foundation after a vote].