# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [milestoned]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  spec-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Beginning review of spec milestone, ${{ github.event.issue.number }} title, ${{ github.event.issue.title }}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "mailestone info; ${{ github.event.issue.milestone.title }} @ ${{ github.event.issue.milestone.description }}",
          echo "...due; ${{ github.event.issue.milestone.due_on }}".
